apiVersion: v1
kind: Secret
metadata:
  name: oficina-secrets
  namespace: oficina
  labels:
    app.kubernetes.io/name: oficina
type: Opaque
stringData:
  JWT_SECRET: "CHANGE-ME-IN-PRODUCTION"
  SMTP_USER: "your-smtp-user@gmail.com"
  SMTP_PASSWORD: "your-app-password"
  DATABASE_URL: "PLACEHOLDER_DB_URL"
  CPF_VALIDATOR_LAMBDA_ARN: "PLACEHOLDER_LAMBDA_ARN"
