apiVersion: v1
kind: Secret
metadata:
  name: oficina-secrets
  namespace: oficina
  labels:
    app.kubernetes.io/name: oficina
type: Opaque
stringData:
  JWT_SECRET: "CHANGE-ME-IN-PRODUCTION"
  DB_PASSWORD: "oficina123"
  SMTP_USER: "your-smtp-user@gmail.com"
  SMTP_PASSWORD: "your-app-password"
