apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: oficina-api-tgb
  namespace: oficina
spec:
  serviceRef:
    name: oficina-api
    port: 80
  targetGroupARN: TARGET_GROUP_ARN_PLACEHOLDER
  targetType: ip

